---
- name: Ensure nginx_stream_path exists.
  file:
    path: "{{ nginx_stream_path }}"
    state: directory
  notify: reload nginx

- name: Add managed stream config file (if any streams are configured).
  template:
    src: streams.j2
    dest: "{{ nginx_stream_path }}/{{ nginx_streams_filename }}"
    mode: 0644
  when: nginx_streams|length > 0
  notify: reload nginx

- name: Remove managed stream config file (if no streams are configured).
  file:
    path: "{{ nginx_stream_path }}/{{ nginx_streams_filename }}"
    state: absent
  when: nginx_streams|length == 0
  notify: reload nginx
